### PR TITLE
Adding support for watchedNamespaces and watchedPodNamePrefixes

### PR DESCRIPTION
**Pull request by tcyran**
Hey

I'm adding support for watchedNamespaces and watchedPodNamePrefixes which was requested in #14.
It has reverse logic to ignore*

### CODE REVIEW

**Comment by able8** [comment]
Thanks for your contribution. 
Sorry, we might not merge this PR since the ignoredNamespaces and watchedNamespaces seem duplicated.

**Comment by tcyran** [comment]
> Thanks for your contribution. Sorry, we might not merge this PR since the ignoredNamespaces and watchedNamespaces seem duplicated.

Hey
It introduced opposite logic.
With ignoredNamespaces you're choosing which namespaces you don't want to "see"
With watchedNamespaces you're choosing only those which you want to "see"

**Comment by able8** [comment]
I see, but I'm concerned that supporting both ignoredNamespaces and watchedNamespaces may confuse users.

**Comment by tcyran** [comment]
> I see, but I'm concerned that supporting both ignoredNamespaces and watchedNamespaces may confuse users.

Both can coexists and even be used together but I get your point.
On the other hand if you have 100 namespaces and you want to observe only 5 of them setting ignoredNamespaces and updating it after every ns creation is painful. So maybe we can achieve it in some other way

**Comment by vaibhavjain882** [comment]
I'd also vote for inclusion. We have a use case where we want to monitor only one namespace out of hundreds of namespaces.

**Comment by jeremych1000** [comment]
Definitely need this! We run a cluster for many tenants which are dynamically created. We are using this to monitor our system namespaces - it's not realistic to have a 200 long ignore list!

**Comment by jeremych1000** [comment]
> I'd also vote for inclusion. We have a use case where we want to monitor only one namespace out of hundreds of namespaces. @tcyran I will build a docker image from your changes and test it in my infrastructure.

Did you push this image anywhere? :)

**Comment by jeremych1000** [comment]
Alternatively - a label selector on namespaces, so I can ask to watch only namespaces with specific labels.

**Comment by able8** [comment]
Thanks. We have added this feature, see https://github.com/airwallex/k8s-pod-restart-info-collector/blob/master/CHANGELOG.md#v140---2023-05-12

**Pull request closed without merging**
