### PR TITLE
 updated controller.go to fix resource specification bug for a container

### PR DESCRIPTION
**Pull request by samyswam**
To fix below issue
https://github.com/airwallex/k8s-pod-restart-info-collector/issues/26

### CODE REVIEW

**Comment by samyswam** [comment]
@able8 please review and merge this bug fix

**Comment by samyswam** [comment]
Can someone review this please?

**Comment by able8** [comment]
Hello @samyswam, thank you for your valuable contribution in fixing the bug. 
Unfortunately, I cannot merge your pull request at the moment due to the Contributor License Agreement (CLA). 
See https://github.com/airwallex/Auticuro/blob/master/Contribution.md#legal-requirements
Would it be okay if I make the necessary changes using my account?

**Comment by samyswam** [comment]
yes @able8 you can make necessary changes using your account

**Comment by able8** [comment]
@samyswam  Thanks for your contribution and understanding.  
You can [submit the CLA](https://github.com/airwallex/Auticuro/blob/master/Contribution.md#legal-requirements) if you want to contribute to this project later.
I will close this PR and create a new one to fix this bug.

**Pull request closed without merging**
